apiVersion: batch/v1
kind: CronJob
metadata:
  name: server-deletion
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: server-deletion
            image: server-deletion
            imagePullPolicy: Never
          restartPolicy: OnFailure
          serviceAccountName: serveupapi
