apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: serveupapi
rules:
- apiGroups: ["", "apps"]
  resources: ["services", "deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]