apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-role-tomi-binding
  namespace: user-tomi
subjects:
- kind: ServiceAccount
  name: serveupapi
  namespace: default
roleRef:
  kind: Role
  name: service-role-tomi
  apiGroup: rbac.authorization.k8s.io