apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: user-franco
  name: service-role-franco
rules:
- apiGroups: ["", "apps"]
  resources: ["services", "deployments"]
  verbs: ["get", "watch", "list", "create"]